### ISSUE TITLE
BUG: Need graceful error message when passing a path object as `depends_on`

### ISSUE THREAD

**Issue by hmgaudecker** [pytask-dev/pytask#75]
- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pytask.

- [ ] (optional) I have confirmed this bug exists on the `main` branch of pytask.

---

#### To reproduce

Pass a pathlib.Path object as dependency to some task which points to a file that does not exist.

#### Problem description

The error message is cryptic even to the semi-initiated and it does not provide information on which file 
```pytb
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/epp/lib/python3.8/site-packages/_pytask/resolve_dependencies.py", line 144, in _check_if_root_nodes_are_available
    dag.nodes[node]["node"].state()
  File "/home/xxx/miniconda3/envs/epp/lib/python3.8/site-packages/_pytask/nodes.py", line 180, in state
    raise NodeNotFoundError
_pytask.exceptions.NodeNotFoundError

During handling of the above exception, another exception occurred:

ValueError: A node must be defined in a child of 'paths'.
```

#### Expected Output

At a very minimum, line 180 of `nodes.py` should become 

```
raise NodeNotFoundError(self.value)
```
but a more graceful error message pointing the user at what is causing this might be useful!

**Comment by tobiasraabe** [comment]
I cannot reproduce it with 0.0.13 and 0.0.11. I imagine your setup is like this:

```python
import pytask
from pathlib import Path


@pytask.mark.depends_on(Path("some_text.txt"))
def task_hm():
    pass
```

Then, executing pytask yields

```console
(pytask) C:\Users\tobia\git\pytask [main ≡ +3 ~0 -0 !]> pytask .\example\ -k task_hm
======================================= Start pytask session ========================================
Platform: win32 -- Python 3.7.10, pytask 0.0.13, pluggy 0.13.1
Root: C:/Users/tobia/git/pytask/example
Collected 1 task. Deselected 8 tasks.
============================== Failures during resolving dependencies ===============================

_pytask.exceptions.ResolvingDependenciesError: There are some dependencies missing which do not exist and are not produced by any task. See the following dictionary with missing nodes as keys and dependent tasks as values.

{'example/some_text.txt': ['example/task_example.py::task_hm']}

=====================================================================================================
```

BTW, in the upcoming release it will be the following. Please, leave a comment if you like it or have another suggestion.

```console
(pytask) C:\Users\tobia\git\pytask [rich ≡ +3 ~0 -0 !]> pytask .\example\ -k task_hm
──────────────────────────────────────── Start pytask session ────────────────────────────────────────
Platform: win32 -- Python 3.7.10, pytask 0.0.13+22.g0263743, pluggy 0.13.1
Root: C:\Users\tobia\git\pytask\example
Collected 1 task. Deselected 8 tasks.

─────────────────────────────── Failures during resolving dependencies ───────────────────────────────

ResolvingDependenciesError: Some dependencies do not exist or are not produced by any task. See the
following tree which shows which dependencies are missing for which tasks.

Missing dependencies:
└── 📄 example/some_text.txt
    └── 📝 example/task_example.py::task_hm

──────────────────────────────────────────────────────────────────────────────────────────────────────
```
